name: report_it_ips
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  auto_size_text: ^3.0.0
  change_app_package_name: ^1.1.0
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.0
  firebase_core: ^2.12.0
  firebase_database: ^10.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_launcher_icons: ^0.13.1
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.1
  google_maps_flutter: ^2.2.6
  google_sign_in: ^6.1.4
  intl: any
  path_provider: ^2.0.15
  permission_handler: ^10.2.0
  provider: ^6.0.5
  shared_preferences: ^2.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/backgrounds/
    - assets/images/icons/
    - assets/images/profile/default_profile.png
    - assets/map_styles/
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: assets/images/icons/icon.png
  min_sdk_android: 21

# Recreate splash screen with:
# flutter clean && flutter pub get && flutter pub run flutter_native_splash:create
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash_screen/splash.png
  android_12:
    image: assets/images/splash_screen/android12_splash.png
